/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 21.02.2026 20:58:56

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 8
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 10128;
#else
constexpr int kTensorArenaSize = 9104;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_RESHAPE, OP_CONV_2D, OP_MAX_POOL_2D, OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,3960 } };
const TfArray<1, float> quant0_scale = { 1, { 0.0037224264815449715, } };
const TfArray<1, int> quant0_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[4] = { 1, 1, 99, 40, };
const TfArray<1, int> tensor_dimension1 = { 1, { 4 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data2[4] = { 1, 99, 1, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[4] = { 1, 1, 50, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data4[4] = { 1, 50, 1, 16, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data5[2] = { -1, 400, };
const TfArray<1, int> tensor_dimension5 = { 1, { 2 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data6[4] = { 470, 1249, 97, -2019, };
const TfArray<1, float> quant6_scale = { 1, { 0.00020445245900191367, } };
const TfArray<1, int> quant6_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data7[4*400] = { 
  35, 33, -1, 7, -3, 10, -73, 11, 18, 6, 23, 34, 16, 1, -6, 3, 38, 29, -16, -8, -5, 19, -43, 10, -3, 1, 20, 5, 10, -6, -15, -7, 23, 45, -8, -21, 9, 13, -31, 6, -2, 0, 1, 12, 29, -10, -16, 0, 24, 18, 3, -12, 11, 5, -30, 8, -11, 8, 21, -12, 5, 12, 18, -2, 25, 2, -7, -7, -6, 16, -14, 4, -15, -6, 4, 5, 11, 23, 17, -17, 14, 16, -14, 2, -3, 10, 23, 17, -3, 1, -10, 17, 19, 10, -16, 9, 7, 3, -3, 30, 9, 3, 25, -6, -4, -7, -17, 26, -6, 36, 19, 8, 11, 17, 0, 30, -10, 9, -9, 4, 7, 14, 15, 41, 11, 17, 16, 13, 21, 22, -7, -4, -35, 10, -16, 11, 13, -10, -3, 42, 11, -19, 1, 27, 29, 17, -5, -9, -22, 15, -6, -4, -12, -1, -13, 12, 14, -23, 2, 20, 15, 10, 0, -7, -17, 11, -7, 0, -15, 1, 4, 15, 19, -4, -6, 19, 33, 13, -6, -8, -12, 9, 4, 10, -11, -5, -15, 5, 12, 30, 6, 20, 11, -3, 2, 0, -11, -2, -9, 2, -27, -1, -28, 6, -9, 14, 5, -5, -4, 9, -6, 21, 3, 5, -39, 4, -34, -10, -8, -4, 6, -10, -28, -29, 20, 23, -17, -25, -22, 16, -33, 4, -19, 3, -6, 18, 10, 3, -39, 7, 33, 20, -9, 4, -3, 15, -12, 18, -3, 14, 3, 25, 7, 7, -20, 15, 22, 6, 2, -9, -15, 25, -11, 12, -4, 5, 14, 23, 23, 33, 9, 10, 21, 13, 9, -2, -19, 10, 13, 11, -6, 4, 4, 8, 11, 26, -13, 9, -4, 9, 1, -16, -9, 9, -3, 2, -11, -10, -12, 2, 5, 2, -3, 9, -8, -4, 9, 25, -10, 14, 20, 14, 6, -13, -9, 5, 0, 15, -8, 28, 22, 2, -8, 0, -13, 13, 21, 7, 1, -2, 0, 4, 2, 2, -13, 14, -1, 6, 6, 16, -14, -2, 14, 4, -19, -8, -11, 14, 12, -8, 3, 32, 24, 7, -17, 7, 3, 14, -11, 10, -5, -1, 11, -9, 8, 8, -20, 18, 14, 12, -17, 13, -24, 18, -8, 21, -14, -15, -19, 7, 17, -4, -23, 10, 3, 21, -10, 0, -43, -5, 6, 8, -14, -16, -41, 5, 17, -22, -19, 32, 
  -43, -38, 12, -25, -51, -60, -66, -28, -8, -26, -27, 3, -35, -48, -90, -72, -28, -22, 11, -1, 3, -26, -11, -25, 9, -3, -2, 20, -15, -45, -56, -94, -1, -25, 28, -4, -6, -13, -5, 5, -2, -8, -15, -19, -10, -58, -13, -67, 13, 8, 30, 6, -22, 1, 27, -7, 1, -14, -23, -9, 11, -62, -28, -4, 2, -13, 36, 15, -53, -14, 24, -2, -10, -16, -26, -5, 11, -55, -62, -16, -11, -10, 33, -17, -43, -19, -9, 11, -5, -13, -22, -17, -22, -97, -84, -45, 10, -14, 41, -34, -55, -15, -5, -2, -28, -6, -27, -41, -11, -86, -32, -13, 3, -4, 22, -16, -43, -5, 32, -14, -2, -6, 6, -26, 7, -78, -33, -21, -3, 20, 34, -26, -50, -4, 35, -8, -10, -4, 9, -34, 3, -60, -31, -19, -8, -10, 45, 10, -41, 10, 44, 3, 14, -1, 24, 9, -2, -25, -37, -5, -6, -5, 43, 10, -67, -10, 60, -5, 14, 2, 20, 5, -24, -58, -10, -31, 3, 16, 23, 16, -66, 20, 17, -1, 33, 11, 46, 12, 18, -38, -22, 15, 7, -3, 31, -35, -41, 0, 38, 5, 15, -26, -15, -7, 6, -90, -31, -17, -23, -41, 24, -25, -17, -26, 8, -16, -10, 4, -17, -23, -40, -80, -23, -73, -19, -13, 33, 8, -22, -14, 26, -3, 7, 4, -6, -10, -29, -29, -41, -42, 0, 13, 27, 35, -36, 6, -11, 1, -5, -12, -20, 22, 0, -51, -36, -20, -11, 12, 22, 15, -63, -9, 4, -15, -6, -4, -23, 11, 9, -35, -49, -12, -8, -7, 32, 22, -63, -3, 7, -13, -5, -3, -11, 8, -3, -77, -78, -16, -14, -14, 21, -6, -67, -29, -7, -14, -17, -9, -14, 7, -23, -70, -60, 3, 6, 1, 26, -22, -57, -2, 5, -5, -25, -9, -19, -49, 3, -89, -44, -19, -11, 16, 27, -27, -34, 6, 16, 7, -22, -14, -4, -21, -7, -48, -53, -4, 1, 13, 44, -46, -89, 7, 20, -5, -12, -10, -1, -9, 2, -43, -38, -1, -9, 9, 39, -10, -97, -5, 63, 4, -6, 3, -28, -23, -10, -61, -56, -12, -4, -16, 51, 8, -98, -27, 59, -1, 11, -13, -17, 5, -25, -127, -74, -29, -9, -5, 48, -14, -69, -11, 43, -13, 0, -29, -21, -21, -15, -121, -67, -17, 
  -5, -3, -37, -42, 16, -13, 33, 0, -20, -11, -24, -9, -8, 21, 14, -19, 11, -18, -43, -14, 21, 3, 31, -15, -30, -20, -31, -41, -13, 5, 11, -27, 0, 0, -39, -9, 13, -7, -14, 5, -39, -8, -33, -15, -2, 18, 23, -54, 13, -2, -20, -17, 7, 9, -5, -7, -30, -3, -19, -28, -1, 20, 16, -41, 2, 0, -35, -4, 14, -5, 35, -2, -19, 0, -1, -10, -10, -8, 18, -9, 1, -15, -51, 26, 6, 1, -5, -5, -19, 5, -12, -12, -5, 9, 24, -46, 9, -6, -41, -19, 2, -1, -14, 11, -15, 4, -32, 13, -3, 0, 0, -20, 19, -23, -19, -25, 24, -6, 8, 16, -3, -13, -22, -45, -12, -5, 27, -30, -2, -13, -8, -49, 44, 6, 27, -1, -23, -2, -12, -70, -12, 21, 41, -39, 5, -23, -32, -39, 25, 4, 16, 11, -23, 5, 5, -81, -14, 27, 31, -46, -12, -11, -5, -19, 26, 0, 3, 23, -38, 3, -25, -72, 4, 2, 41, -52, -4, -23, -42, -56, 18, -13, -9, 2, -26, -5, -5, -38, 5, -5, 9, -55, -24, -9, -25, -24, 16, 2, -17, 6, -9, -7, -32, -12, -17, 9, 16, -42, 6, -25, -20, -36, 14, -14, -24, -11, -27, 2, -24, -52, -5, 18, 13, -44, -10, -23, -7, -26, 25, 2, -6, -10, -23, -18, 1, -76, 6, -11, 13, -14, -12, 3, -14, -34, 16, -6, 12, 6, -26, -2, -28, -60, 6, 10, 17, -30, 1, 1, -59, -48, 37, -1, -3, 7, -34, -8, -6, -59, -8, -14, 3, -46, -10, 0, -40, -26, 34, 9, -4, 15, -26, -7, -25, -105, 6, -2, 24, -44, -11, -5, -39, -38, 22, -6, 2, 6, -24, 7, -27, -83, -1, -3, 11, -5, -9, -10, -39, -34, 26, -13, -7, 5, -27, -5, -38, -58, 15, 20, 21, -36, -12, -16, -38, -54, 42, -11, -18, 16, -30, 4, -31, -50, -8, 13, 4, -43, -20, -18, -43, -60, 34, -12, -14, 1, -35, 5, -14, -69, -1, 22, 39, -45, -10, -22, -37, -40, 38, -20, 18, 10, -11, -10, -27, -56, -11, 30, 26, -48, 2, -10, -80, -52, 32, -13, -33, -1, -14, -16, -44, -46, 7, 24, 29, -49, -4, -19, -60, -49, 53, -3, -32, 14, -37, -18, -35, -62, 17, 37, 28, -79, 
  -3, -3, 8, 17, 14, -5, 109, 4, 1, 15, 11, -18, -6, 14, 60, 36, -28, -15, -3, 37, -5, -31, 47, 6, 20, 11, 5, -7, -25, 31, 23, 31, -29, -43, -19, 21, -19, -23, 47, -17, 11, 11, 10, 11, -35, 25, 3, 33, -33, -12, -6, 33, -5, -24, 18, -5, 28, 7, 7, 19, -43, -9, -19, 22, -50, -2, -12, 8, -9, 5, 14, -5, 23, 32, 26, 8, -37, -2, -3, 3, -41, -6, -20, 32, 9, -9, -11, -18, 33, 34, 31, 1, -32, -6, 21, -3, -18, 9, -13, -4, -9, 9, -21, -13, 22, 34, 40, -8, 19, 0, 14, 7, -13, -9, -31, -4, -1, -16, -1, -18, 15, -1, 4, -7, 2, -2, -14, -7, -24, -21, -36, 23, 0, -22, 19, -14, 19, 40, 8, -3, -20, 13, -10, 5, -10, -20, -20, 32, -3, 10, 7, -5, 20, 15, 13, -2, -22, -19, 3, 1, -33, -8, -27, 11, -2, -7, -2, -7, 10, 12, 3, 0, -4, -6, 14, 8, -13, -2, -9, 6, 11, -5, -10, -4, 9, 11, -6, -4, 0, 4, -11, -9, -4, 2, -6, 2, -9, 2, -3, 0, 25, 32, 39, -5, 3, 17, -8, 10, 9, 4, -22, 16, -15, 31, 46, 11, 54, 33, 14, 2, -3, 29, 18, 57, -24, 3, -15, 29, -9, -8, 30, -6, 23, 24, 32, -1, -14, 11, 20, 26, -35, -19, -11, 9, -6, -12, 14, -15, 5, 11, 9, -21, -13, -13, 17, -12, -25, -3, -7, 9, 2, -21, 14, 1, 5, 25, 12, -3, -18, -7, -5, -9, -15, -14, -15, -11, 3, -3, -1, 7, 11, 20, 28, -7, 2, -16, 30, 10, -1, 6, -10, 17, -15, -20, 7, -3, 31, 26, 36, 22, 6, 12, 9, -10, 1, 6, -11, 1, -20, 0, -5, 11, 24, 20, 39, 38, -8, -10, 2, 0, -12, -22, -8, 17, -16, 1, -3, -5, 11, 24, 19, 6, -8, 5, 8, -11, -10, -1, -14, 27, -14, -21, -10, 3, 22, 21, 19, 28, 4, 7, -1, -18, -20, -6, -7, 15, -17, -2, 7, 10, 43, -3, 30, 16, -13, -3, -2, -1, -18, 2, -14, 4, 11, -26, -3, -20, 30, 34, 31, 17, -1, 27, 31, 14, -4, 4, -14, 25, 17, 4, -25, 4, 44, 51, 53, 44, -4, 13, 19, 0, 
};
const TfArray<2, int> tensor_dimension7 = { 2, { 4,400 } };
const TfArray<1, float> quant7_scale = { 1, { 0.0097610186785459518, } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&g0::quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data8[16] = { 1415, -1900, 465, -1217, 3124, -1707, -2453, -486, -2786, -3276, -1825, 1495, 98, 1150, -721, -331, };
const TfArray<1, int> tensor_dimension8 = { 1, { 16 } };
const TfArray<16, float> quant8_scale = { 16, { 6.7389642936177552e-05, 6.539708556374535e-05, 0.00010733226372394711, 8.5882376879453659e-05, 6.7045744799543172e-05, 7.5338401074986905e-05, 8.5341693193186074e-05, 6.5040054323617369e-05, 6.6770429839380085e-05, 6.4954772824421525e-05, 0.00013422097254078835, 0.00010517182818148285, 8.5940198914613575e-05, 0.00010250541527057067, 6.9618741690646857e-05, 8.4189450717531145e-05, } };
const TfArray<16, int> quant8_zero = { 16, { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data9[16*1*3*8] = { 
  /* [0][0][][] */ -107,67,1,40,-75,4,37,60, -127,55,-26,-14,-86,-9,80,-23, -96,87,-20,17,-86,-8,57,51, 
  /* [1][0][][] */ -116,86,-24,60,-51,-39,-23,61, -127,17,-79,18,-22,38,35,113, -53,50,-29,-7,-43,-44,-7,49, 
  /* [2][0][][] */ 84,14,-10,10,24,-50,102,37, 121,2,36,29,31,-59,101,44, 68,20,33,-10,9,-37,127,1, 
  /* [3][0][][] */ 4,-41,127,-47,79,0,-92,0, -33,-34,-22,2,41,-6,-68,24, -47,7,-25,-12,9,-11,-32,16, 
  /* [4][0][][] */ -31,-34,-26,-60,-127,4,-80,-74, -54,-27,0,-67,-76,101,-72,-108, -22,29,15,-59,-50,125,-84,-79, 
  /* [5][0][][] */ -127,52,8,30,-52,-38,-32,86, -110,46,-2,-13,-25,26,-46,2, -92,83,-26,30,-34,-6,-31,64, 
  /* [6][0][][] */ 113,53,43,21,-20,-38,65,26, 118,-17,127,-76,11,-1,23,14, 84,-85,7,10,56,6,49,-12, 
  /* [7][0][][] */ -127,73,-67,-73,-82,53,44,37, -31,76,-27,47,-22,18,23,41, -66,9,-71,-26,-4,1,61,26, 
  /* [8][0][][] */ -85,-50,127,58,71,-15,-12,41, -105,-35,-51,91,107,-6,-91,79, -101,-32,92,57,48,29,-72,-11, 
  /* [9][0][][] */ -95,-73,95,35,17,26,5,10, -127,-50,46,-52,104,23,-41,17, -112,-47,30,58,105,20,-36,63, 
  /* [10][0][][] */ -103,-28,7,30,39,-2,7,-3, -104,-21,35,27,40,9,-16,16, -127,-2,44,45,9,17,-17,38, 
  /* [11][0][][] */ -68,20,13,22,22,-12,-127,-21, -35,0,48,-6,68,-32,-118,19, -25,-14,-38,19,-19,-41,-114,10, 
  /* [12][0][][] */ -127,53,-23,52,-45,-1,48,28, -88,29,-40,-26,-65,24,-22,5, -68,57,-37,1,-27,-12,-3,48, 
  /* [13][0][][] */ -39,-35,35,-54,-25,68,-127,-79, -10,-13,16,-30,-7,-5,-124,-80, -37,-21,67,-26,70,-4,-127,-4, 
  /* [14][0][][] */ -10,-3,65,-14,-46,109,70,-90, -34,26,107,-23,-28,75,55,-127, -10,-64,16,33,1,-6,47,-105, 
  /* [15][0][][] */ -12,57,76,-26,-13,-27,-45,83, 11,18,105,-24,-20,-31,-43,36, 4,-25,127,-29,-25,-17,-26,36, 
};
const TfArray<4, int> tensor_dimension9 = { 4, { 16,1,3,8 } };
const TfArray<16, float> quant9_scale = { 16, { 0.0047931955195963383, 0.0046514715068042278, 0.0076341778039932251, 0.0061085205525159836, 0.00476873479783535, 0.005358563270419836, 0.0060700634494423866, 0.0046260771341621876, 0.004749152809381485, 0.004620011430233717, 0.0095466794446110725, 0.0074805133044719696, 0.0061126328073441982, 0.0072908601723611355, 0.00495174340903759, 0.0059881084598600864, } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&g0::quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data10[8] = { 1563, -2098, -4299, -1053, 7156, -5358, 338, -1035, };
const TfArray<1, int> tensor_dimension10 = { 1, { 8 } };
const TfArray<8, float> quant10_scale = { 8, { 3.6360997910378501e-05, 2.1968626242596656e-05, 1.8129383533960208e-05, 1.2925311239087023e-05, 2.1443989680847153e-05, 2.5185376216541044e-05, 3.7681784306187183e-05, 1.9885319488821551e-05, } };
const TfArray<8, int> quant10_zero = { 8, { 0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&quant10_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data11[8*1*3*40] = { 
  /* [0][0][][] */ -121,113,-4,-83,16,-11,19,-19,59,-48,-6,-15,-65,-33,-48,-7,6,30,49,-2,8,-51,-21,18,7,-14,5,6,23,-15,-36,-14,4,-23,-15,-26,20,15,46,34, -127,66,-76,-38,-8,7,34,62,62,-39,26,19,-108,5,1,2,12,49,44,30,-30,-30,-37,-17,-29,-22,3,18,31,-12,-38,-10,-24,-30,-29,-15,33,41,24,22, -93,76,60,-77,76,-13,6,3,88,-12,-17,-36,-67,-49,-64,-26,-3,33,64,2,3,-59,-34,-4,-18,-37,-39,22,-3,-7,-45,-51,-13,-25,-29,-26,13,48,57,37, 
  /* [1][0][][] */ -127,-62,-48,-8,-106,62,-28,46,-28,-7,8,10,54,-13,27,45,-42,-3,35,21,-12,-33,24,32,21,-27,-24,7,5,6,-7,-45,-20,16,21,42,3,-3,15,-17, -51,-46,-54,-57,-60,43,17,33,-30,-31,11,26,48,-18,-40,59,-5,-20,-23,-27,-4,14,-11,7,-25,-13,4,1,13,24,-23,-15,-18,28,9,12,7,12,8,-24, -50,-67,-21,-82,-97,39,11,3,-75,7,-17,59,54,-13,-15,39,-16,37,26,-23,-33,-6,-18,33,26,28,-16,53,9,-28,4,-28,1,-36,-10,46,48,25,-5,35, 
  /* [2][0][][] */ 107,-32,10,112,74,19,74,67,23,35,62,-3,30,-55,-32,15,25,-44,14,-10,-8,-53,-47,-21,8,-6,-18,-27,-7,-11,5,14,-66,2,6,-50,-33,-75,-47,-57, 86,-69,42,93,127,56,62,34,77,23,77,-17,0,-9,30,-4,-54,-46,14,4,-29,-5,-54,-14,-30,49,-11,10,-23,-1,13,24,-79,-37,-53,-65,-96,-22,-73,-71, 76,-79,28,84,117,50,88,97,70,16,-14,-5,8,-18,-12,10,-39,-61,21,-62,-17,-26,-78,-18,29,-21,8,-20,18,67,58,-10,-28,-72,-2,-46,-35,12,-41,-44, 
  /* [3][0][][] */ -103,-89,-54,-75,28,-56,9,-48,0,-80,-13,-59,-36,-11,-17,-27,28,-8,-6,-28,13,41,50,53,17,69,66,-29,72,53,45,59,74,57,34,26,-34,-20,-105,-31, -127,-120,-62,-77,10,-6,-4,-79,-3,18,-47,-26,-49,-63,9,-55,26,9,-38,-8,16,11,-5,58,-6,-22,51,-21,26,7,66,67,39,13,-22,-26,-22,-64,8,-90, -17,-87,-3,-88,12,22,-10,-24,-118,-7,38,-52,-80,-9,-92,1,-18,-33,-58,7,-71,16,-44,13,-33,8,55,21,61,-21,65,-26,16,7,-32,2,2,-73,-92,-81, 
  /* [4][0][][] */ 27,-70,-39,127,90,8,-33,14,38,23,-52,-5,-73,-12,-34,-62,-75,-50,-15,-24,-5,-28,-38,-12,-55,6,9,23,19,-2,-9,20,-4,7,32,-30,-16,23,-29,-12, 13,-58,-23,66,105,-5,-2,-55,54,15,-27,-25,-84,-17,-56,-92,-72,-23,20,-13,0,8,5,17,-27,49,18,1,1,42,-8,44,-12,-7,47,16,-21,4,-46,-25, 59,-70,-47,84,103,-7,-8,-6,53,9,-33,4,-49,5,-54,-73,-75,-52,13,18,26,11,5,-7,-11,-1,-4,15,-1,49,46,-14,58,45,3,33,36,39,-10,-60, 
  /* [5][0][][] */ 20,125,83,66,15,-4,-4,15,35,20,-22,11,13,26,8,0,-14,1,-7,25,-9,19,32,-26,10,-28,5,2,-30,25,-22,30,-10,-31,-8,-21,-40,-46,9,-26, 9,104,121,54,10,-15,-11,-11,23,-20,-43,-45,-3,26,4,-8,5,-16,20,28,24,7,21,21,-7,6,-24,6,-2,2,-10,-9,-44,-12,-51,-38,-28,-8,-27,-40, 80,111,127,45,8,17,9,-1,46,29,4,-7,5,28,2,5,33,-24,-4,-25,26,51,-9,17,9,-27,27,9,-3,-15,8,26,-24,-53,-52,-52,-35,-53,-5,12, 
  /* [6][0][][] */ -87,125,-21,-80,-13,23,-34,-40,37,-76,-11,-21,-63,-1,2,8,8,54,34,9,-7,-15,-13,13,-7,-12,15,21,11,-7,3,-35,-9,-42,-43,-6,-13,33,17,5, -91,46,74,-57,-5,35,-8,49,61,-25,-27,9,-56,23,18,-8,-8,10,45,22,-14,-49,-24,-8,-27,9,-17,27,-4,-12,16,-3,-37,-16,-45,-7,29,31,10,4, -106,127,-23,-61,-18,-14,-22,-33,113,-34,-7,-38,-37,-9,-23,1,37,4,37,6,1,-44,1,0,2,-14,-34,9,4,21,-5,-15,-14,-7,-29,5,3,7,14,23, 
  /* [7][0][][] */ -51,-85,-47,12,13,24,-22,6,-72,-19,65,-7,29,-36,-19,37,-16,38,-22,-21,-32,-8,-26,10,29,5,14,62,48,33,-19,-24,32,43,13,-6,36,7,15,-41, -98,-97,-78,-29,-47,-14,15,18,-62,19,61,-3,29,-9,-50,10,-43,-15,-3,-45,-24,-11,23,37,5,4,-5,52,32,-11,-42,-9,31,23,46,29,30,29,-10,-14, -84,-127,-89,-23,-37,15,-2,-4,-71,18,17,26,-34,3,-6,48,-4,26,12,-22,-28,-4,28,44,-27,49,19,53,6,24,8,26,-23,-12,-18,26,-21,-14,14,-14, 
};
const TfArray<4, int> tensor_dimension11 = { 4, { 8,1,3,40 } };
const TfArray<8, float> quant11_scale = { 8, { 0.0097680902108550072, 0.005901695229113102, 0.0048703132197260857, 0.0034722811542451382, 0.0057607558555901051, 0.0067658494226634502, 0.010122909210622311, 0.0053420313633978367, } };
const TfLiteAffineQuantization quant11 = { (TfLiteFloatArray*)&quant11_scale, (TfLiteIntArray*)&g0::quant10_zero, 0 };
const TfArray<4, int> tensor_dimension12 = { 4, { 1,1,99,40 } };
const TfArray<4, int> tensor_dimension13 = { 4, { 1,1,99,8 } };
const TfArray<1, float> quant13_scale = { 1, { 0.014059440232813358, } };
const TfLiteAffineQuantization quant13 = { (TfLiteFloatArray*)&quant13_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<4, int> tensor_dimension14 = { 4, { 1,99,1,8 } };
const TfArray<4, int> tensor_dimension15 = { 4, { 1,50,1,8 } };
const TfArray<4, int> tensor_dimension16 = { 4, { 1,1,50,8 } };
const TfArray<4, int> tensor_dimension17 = { 4, { 1,1,50,16 } };
const TfArray<1, float> quant17_scale = { 1, { 0.02094581164419651, } };
const TfLiteAffineQuantization quant17 = { (TfLiteFloatArray*)&quant17_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<4, int> tensor_dimension18 = { 4, { 1,50,1,16 } };
const TfArray<4, int> tensor_dimension19 = { 4, { 1,25,1,16 } };
const TfArray<2, int> tensor_dimension20 = { 2, { 1,400 } };
const TfArray<2, int> tensor_dimension21 = { 2, { 1,4 } };
const TfArray<1, float> quant21_scale = { 1, { 0.54557251930236816, } };
const TfArray<1, int> quant21_zero = { 1, { 48 } };
const TfLiteAffineQuantization quant21 = { (TfLiteFloatArray*)&quant21_scale, (TfLiteIntArray*)&quant21_zero, 0 };
const TfArray<1, float> quant22_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant22 = { (TfLiteFloatArray*)&quant22_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfLiteReshapeParams opdata0 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs0 = { 2, { 0,1 } };
const TfArray<1, int> outputs0 = { 1, { 12 } };
const TfLiteConvParams opdata1 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs1 = { 3, { 12,11,10 } };
const TfArray<1, int> outputs1 = { 1, { 13 } };
const TfLiteReshapeParams opdata2 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs2 = { 2, { 13,2 } };
const TfArray<1, int> outputs2 = { 1, { 14 } };
const TfLitePoolParams opdata3 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs3 = { 1, { 14 } };
const TfArray<1, int> outputs3 = { 1, { 15 } };
const TfLiteReshapeParams opdata4 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs4 = { 2, { 15,3 } };
const TfArray<1, int> outputs4 = { 1, { 16 } };
const TfLiteConvParams opdata5 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs5 = { 3, { 16,9,8 } };
const TfArray<1, int> outputs5 = { 1, { 17 } };
const TfLiteReshapeParams opdata6 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs6 = { 2, { 17,4 } };
const TfArray<1, int> outputs6 = { 1, { 18 } };
const TfLitePoolParams opdata7 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs7 = { 1, { 18 } };
const TfArray<1, int> outputs7 = { 1, { 19 } };
const TfLiteReshapeParams opdata8 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs8 = { 2, { 19,5 } };
const TfArray<1, int> outputs8 = { 1, { 20 } };
const TfLiteFullyConnectedParams opdata9 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs9 = { 3, { 20,7,6 } };
const TfArray<1, int> outputs9 = { 1, { 21 } };
const TfLiteSoftmaxParams opdata10 = { 1 };
const TfArray<1, int> inputs10 = { 1, { 21 } };
const TfArray<1, int> outputs10 = { 1, { 22 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 3968), (TfLiteIntArray*)&g0::tensor_dimension0, 3960, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 8, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data7, (TfLiteIntArray*)&g0::tensor_dimension7, 1600, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data8, (TfLiteIntArray*)&g0::tensor_dimension8, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data9, (TfLiteIntArray*)&g0::tensor_dimension9, 384, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data10, (TfLiteIntArray*)&g0::tensor_dimension10, 32, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data11, (TfLiteIntArray*)&g0::tensor_dimension11, 960, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant11))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension12, 3960, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 3968), (TfLiteIntArray*)&g0::tensor_dimension13, 792, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension14, 792, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension15, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension16, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension17, 800, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension18, 800, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension19, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension20, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 400), (TfLiteIntArray*)&g0::tensor_dimension21, 4, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant21))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension21, 4, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant22))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 23, };
const size_t tflNodes_subgraph_index[] = {0, 11, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  22, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_909737_3_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 23;
  for (size_t i = 0; i < 23; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_RESHAPE] = Register_RESHAPE();
  registrations[OP_CONV_2D] = Register_CONV_2D();
  registrations[OP_MAX_POOL_2D] = Register_MAX_POOL_2D();
  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_909737_3_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_909737_3_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_909737_3_invoke() {
  for (size_t i = 0; i < 11; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_909737_3_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
